[package]
name = "akasio-rust"
version = "0.1.0"
authors = ["K4YT3X <k4yt3x@k4yt3x.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
actix-web = "3"
clap = "2"
env_logger = "0.8"
log = "0.4"
serde_json = "1"